[main_server]
192.168.1.138 ansible_user=ant target_dir=/home/ant/1progr/matrixDeploy

[public_ip_server]
matrix.vobler-tech.space ansible_user=root target_dir=/root/matrix

[public_ip_server]
matrix.vobler-tech.space ansible_user=root target_dir=/root/matrix
